[project]
name = "projeto-brasileirao"
version = "0.1.0"
description = ""
authors = [
    {name = "Jean Alves",email = "jean_prog@hotmail.com"}
]
readme = "README.md"
requires-python = "=3.11.5"
dependencies = [
    "apache-airflow (>=3.1.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
